function h1 = amc_menuprog()
% This is the machine-generated representation of a Handle Graphics object
% and its children.  Note that handle values may change when these objects
% are re-created. This may cause problems with any callbacks written to
% depend on the value of the handle at the time the object was saved.
% This problem is solved by saving the output as a FIG-file.
% 
% To reopen this object, just type the name of the M-file at the MATLAB
% prompt. The M-file and its associated MAT-file must be on your path.
% 
% NOTE: certain newer features in MATLAB may not have been saved in this
% M-file due to limitations of this format, which has been superseded by
% FIG-files.  Figures which have been annotated using the plot editor tools
% are incompatible with the M-file/MAT-file format, and should be saved as
% FIG-files.



appdata = [];
appdata.GUIDEOptions = struct(...
    'active_h', [], ...
    'taginfo', struct(...
    'figure', 2, ...
    'text', 2), ...
    'override', 1, ...
    'resize', 'simple', ...
    'accessibility', 'on', ...
    'mfile', 0, ...
    'callbacks', 0, ...
    'singleton', 1, ...
    'blocking', 0, ...
    'syscolorfig', 1, ...
    'release', 12);
appdata.lastValidTag = 'amc_menu';
appdata.GUIDELayoutEditor = [];

h1 = figure(...
'Units','normalized',...
'PaperUnits',get(0,'defaultfigurePaperUnits'),...
'Color',[0.831372549019608 0.815686274509804 0.784313725490196],...
'Colormap',[0 0 0.5625;0 0 0.625;0 0 0.6875;0 0 0.75;0 0 0.8125;0 0 0.875;0 0 0.9375;0 0 1;0 0.0625 1;0 0.125 1;0 0.1875 1;0 0.25 1;0 0.3125 1;0 0.375 1;0 0.4375 1;0 0.5 1;0 0.5625 1;0 0.625 1;0 0.6875 1;0 0.75 1;0 0.8125 1;0 0.875 1;0 0.9375 1;0 1 1;0.0625 1 1;0.125 1 0.9375;0.1875 1 0.875;0.25 1 0.8125;0.3125 1 0.75;0.375 1 0.6875;0.4375 1 0.625;0.5 1 0.5625;0.5625 1 0.5;0.625 1 0.4375;0.6875 1 0.375;0.75 1 0.3125;0.8125 1 0.25;0.875 1 0.1875;0.9375 1 0.125;1 1 0.0625;1 1 0;1 0.9375 0;1 0.875 0;1 0.8125 0;1 0.75 0;1 0.6875 0;1 0.625 0;1 0.5625 0;1 0.5 0;1 0.4375 0;1 0.375 0;1 0.3125 0;1 0.25 0;1 0.1875 0;1 0.125 0;1 0.0625 0;1 0 0;0.9375 0 0;0.875 0 0;0.8125 0 0;0.75 0 0;0.6875 0 0;0.625 0 0;0.5625 0 0],...
'InvertHardcopy',get(0,'defaultfigureInvertHardcopy'),...
'MenuBar','none',...
'Name','ARRAYMATIC MENUS',...
'NumberTitle','off',...
'PaperPosition',[0.6345175 6.345175 20.30456 15.22842],...
'PaperSize',[20.98404194812 29.67743169791],...
'PaperType',get(0,'defaultfigurePaperType'),...
'Position',[0.28046875 0.5009765625 0.4375 0.19921875],...
'Tag','amc_menu',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text1';

h2 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'BackgroundColor',[0 0.513 0.793],...
'FontSize',25,...
'ForegroundColor',[1 1 0],...
'ListboxTop',0,...
'Position',[0.126190476190476 0.396153846153846 0.732142857142857 0.169230769230769],...
'String','aRRayon & sosMA',...
'Style','text',...
'Tag','text1',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'Untitled_27';

h3 = uimenu(...
'Parent',h1,...
'Label','SOSMA',...
'Tag','Untitled_27',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h4 = uimenu(...
'Parent',h3,...
'Callback','COM_RAY(''update sosma'')',...
'Label','UPDATE SOSMA',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h5 = uimenu(...
'Parent',h3,...
'Callback','COM_RAY(''new sosma'')',...
'Label','NEW SOSMA',...
'Separator','on',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h6 = uimenu(...
'Parent',h3,...
'Callback','COM_RAY(''load sosma'')',...
'Label','LOAD SOSMA',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h7 = uimenu(...
'Parent',h3,...
'Callback','QUIT_CURRENT',...
'Label','QUIT SOSMA',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'Untitled_33';

h8 = uimenu(...
'Parent',h3,...
'Callback','COM_RAY(''calculate duplicate rank correlation'')',...
'Label','calculate duplicate rank correlation ',...
'Separator','on',...
'Tag','Untitled_33',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h9 = uimenu(...
'Parent',h3,...
'Callback','COM_RAY( ''find non redundant biol cond'' )',...
'Label','find non redundant conditions',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'Untitled_32';

h10 = uimenu(...
'Parent',h3,...
'Callback','COM_RAY(''check sosma comparisons'')',...
'Label','check comparisons',...
'Separator','on',...
'Tag','Untitled_32',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h11 = uimenu(...
'Parent',h3,...
'Callback','COM_RAY(''print experiment properties'')',...
'Label','print experiment properties',...
'Separator','on',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h12 = uimenu(...
'Parent',h3,...
'Callback','COM_RAY(''print biolcond properties'')',...
'Label','print biolcond properties',...
'Separator','on',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'Untitled_35';

h13 = uimenu(...
'Parent',h3,...
'Callback','COM_RAY(''print biolcond information'')',...
'Label','print biolcond information',...
'Tag','Untitled_35',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'Untitled_36';

h14 = uimenu(...
'Parent',h3,...
'Callback','COM_RAY(''import biolcond information'')',...
'Label','import biolcond information',...
'Tag','Untitled_36',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h15 = uimenu(...
'Parent',h3,...
'Callback','COM_RAY(''calculate point properties'')',...
'Label','calculate point properties',...
'Separator','on',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h16 = uimenu(...
'Parent',h3,...
'Callback','COM_RAY(''display point properties'')',...
'Label','display point properties',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h17 = uimenu(...
'Parent',h3,...
'Callback','COM_RAY(''print point properties'')',...
'Label','print point properties',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h18 = uimenu(...
'Parent',h3,...
'Callback','COM_RAY(''calculate comparison properties'')',...
'Label','calculate comparison properties',...
'Separator','on',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h19 = uimenu(...
'Parent',h3,...
'Callback','COM_RAY(''display comparison properties'')',...
'Label','display comparison properties',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h20 = uimenu(...
'Parent',h1,...
'Label','NETWORK',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h21 = uimenu(...
'Parent',h20,...
'Callback','COM_RAY(''interrogate network'',1)',...
'Label','NEW PROJECT',...
'Separator','on',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'Untitled_17';

h22 = uimenu(...
'Parent',h20,...
'Callback','COM_RAY(''interrogate network'',0)',...
'Label','LOAD A PROJECT',...
'Tag','Untitled_17',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h23 = uimenu(...
'Parent',h20,...
'Callback','QUIT_CURRENT',...
'Label','QUIT NETWORK',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'Untitled_45';

h24 = uimenu(...
'Parent',h20,...
'Callback','COM_RAY(''merge nets'')',...
'Label','MERGE NET',...
'Tag','Untitled_45',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'Untitled_37';

h25 = uimenu(...
'Parent',h20,...
'Callback','COM_RAY(''find non redundant biol cond'')',...
'Label','find non redundant biol cond',...
'Separator','on',...
'Tag','Untitled_37',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h26 = uimenu(...
'Parent',h20,...
'Callback','COM_RAY(''describe new network'')',...
'Label','describe new network',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'Untitled_44';

h27 = uimenu(...
'Parent',h20,...
'Callback','COM_RAY(''clone a network'')',...
'Label','clone a network',...
'Tag','Untitled_44',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h28 = uimenu(...
'Parent',h20,...
'Callback','COM_RAY(''write data for network'')',...
'Label','write data for network',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'Untitled_38';

h29 = uimenu(...
'Parent',h20,...
'Callback','COM_RAY(''write data for network'',1)',...
'Label','write pbs & bat files',...
'Tag','Untitled_38',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'Untitled_39';

h30 = uimenu(...
'Parent',h20,...
'Callback','COM_RAY(''write ranks for network'')',...
'Label','write ranks for network',...
'Tag','Untitled_39',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h31 = uimenu(...
'Parent',h20,...
'Callback','COM_RAY(''construct network'')',...
'Label','construct network',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'Untitled_34';

h32 = uimenu(...
'Parent',h20,...
'Callback','COM_RAY(''delete network'')',...
'Label','delete network',...
'Tag','Untitled_34',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h33 = uimenu(...
'Parent',h20,...
'Callback','COM_RAY(''display q vs ac'')',...
'Label','display Q vs AC',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h34 = uimenu(...
'Parent',h20,...
'Callback','COM_RAY(''prepare network export to keiko'')',...
'Label','prepare export to keiko',...
'Separator','on',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h35 = uimenu(...
'Parent',h20,...
'Callback','COM_RAY(''export network to keiko'')',...
'Label','export to keiko',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h36 = uimenu(...
'Parent',h20,...
'Callback','COM_RAY(''import network from keiko'')',...
'Label','import from keiko',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h37 = uimenu(...
'Parent',h20,...
'Callback','COM_RAY(''display 3D overlap of two networks'')',...
'Label','Display 3D overlap of two networks',...
'Separator','on',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h38 = uimenu(...
'Parent',h20,...
'Callback','COM_RAY(''import diver'')',...
'Label','import gene diver',...
'Separator','on',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h39 = uimenu(...
'Parent',h20,...
'Callback','COM_RAY(''map diver in another chipset'')',...
'Label','map diver in another chipset',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h40 = uimenu(...
'Parent',h20,...
'Callback','EXPORT_MCL',...
'Label','export to markov clustering',...
'Separator','on',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h41 = uimenu(...
'Parent',h20,...
'Callback','COM_RAY(''import markov clustering'')',...
'Label','import from markov clustering',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'Untitled_49';

h42 = uimenu(...
'Parent',h20,...
'Callback','COM_RAY(''import modulator clustering''',...
'Label','import from modulator clustering',...
'Separator','on',...
'Tag','Untitled_49',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'Untitled_47';

h43 = uimenu(...
'Parent',h20,...
'Callback','COM_RAY(''my clustering'')',...
'Label','my clustering',...
'Separator','on',...
'Tag','Untitled_47',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h44 = uimenu(...
'Parent',h20,...
'Callback','COM_RAY(''import GO for display on keiko'')',...
'Label','import GO for display on keiko',...
'Separator','on',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h45 = uimenu(...
'Parent',h20,...
'Callback','COM_RAY(''display on keiko'',''cluster'')',...
'Label','display clusters on keiko',...
'Separator','on',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'Untitled_20';

h46 = uimenu(...
'Parent',h20,...
'Callback','COM_RAY(''export clusters to cytoscape'')',...
'Label','export clusters to cytoscape',...
'Tag','Untitled_20',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h47 = uimenu(...
'Parent',h20,...
'Callback','COM_RAY(''export clusters to generator'')',...
'Label','export clusters to generator',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'Untitled_25';

h48 = uimenu(...
'Parent',h20,...
'Callback','COM_RAY(''construct corr and anti matrix'')',...
'Label','construct corr and anti matrix',...
'Separator','on',...
'Tag','Untitled_25',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h49 = uimenu(...
'Parent',h20,...
'Callback','COM_RAY(''calculate clique'')',...
'Label','calculate cliques',...
'Separator','on',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h50 = uimenu(...
'Parent',h20,...
'Callback','COM_RAY(''recover clique'')',...
'Label','recover cliques',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'Untitled_3';

h51 = uimenu(...
'Parent',h20,...
'Callback','COM_RAY(''merge clique'')',...
'Label','merge cliques',...
'Tag','Untitled_3',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h52 = uimenu(...
'Parent',h20,...
'Callback','COM_RAY(''display clique'')',...
'Label','display cliques',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h53 = uimenu(...
'Parent',h20,...
'Callback','COM_RAY(''print clique'')',...
'Label','print cliques',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h54 = uimenu(...
'Parent',h20,...
'Callback','COM_RAY(''compare clique & IHOP'')',...
'Label','compare clique/iHOP',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h55 = uimenu(...
'Parent',h20,...
'Callback','COM_RAY(''export clique'',''cytoscape'')',...
'Label','export clique to cytoscape',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h56 = uimenu(...
'Parent',h20,...
'Callback','COM_RAY(''export sub network to cytoscape with xy positions'' )',...
'Label','export sub network to cytoscape with xy positions',...
'Separator','on',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h57 = uimenu(...
'Parent',h20,...
'Callback','COM_RAY(''region distribution of a ps list'')',...
'Label','region distribution of a ps list',...
'Separator','on',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'RStat';

h58 = uimenu(...
'Parent',h1,...
'Label','NETWORK STAT',...
'Tag','RStat',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h59 = uimenu(...
'Parent',h58,...
'Callback','COM_RAY(''display q vs ac'')',...
'Label','display quest vs (corr,anti)',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h60 = uimenu(...
'Parent',h58,...
'Callback','COM_RAY(''display network connectivity'')',...
'Label','display network connectivity',...
'Separator','on',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h61 = uimenu(...
'Parent',h58,...
'Callback','COM_RAY(''print network properties'')',...
'Label','print network properties',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h62 = uimenu(...
'Parent',h58,...
'Callback','COM_RAY(''calculate node similarity on replicated probesets'')',...
'Label','calculate node similarity on replicated probesets',...
'Separator','on',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h63 = uimenu(...
'Parent',h58,...
'Callback','COM_RAY(''calculate node similarity between two networks'')',...
'Label','calculate node similarity between two networks',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h64 = uimenu(...
'Parent',h58,...
'Callback','COM_RAY(''display quality of replicated probesets'')',...
'Label','display quality of  replicated probesets',...
'Separator','on',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h65 = uimenu(...
'Parent',h58,...
'Callback','COM_RAY(''display node similarity on replicated probesets'')',...
'Label','display node similarity on replicated probesets',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h66 = uimenu(...
'Parent',h58,...
'Callback','COM_RAY(''display node similarity between two networks on replicated probeset'')',...
'Label','display node similarity between two networks',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h67 = uimenu(...
'Parent',h58,...
'Callback','COM_RAY(''display effect of probe nb on replicated probesets'')',...
'Label','display effect of probe nb on replicated probesets',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h68 = uimenu(...
'Parent',h58,...
'Callback','COM_RAY(''calculate correlation'')',...
'Label','calculate correlation',...
'Separator','on',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'TRANSCRIPTOME';

h69 = uimenu(...
'Parent',h1,...
'Label','TRANSCRIPTOME',...
'Separator','on',...
'Tag','TRANSCRIPTOME',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'L';

h70 = uimenu(...
'Parent',h69,...
'Callback','trs_menucom(''load project'')',...
'Checked','on',...
'Label','LOAD A PROJECT',...
'Tag','L',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 't';

h71 = uimenu(...
'Parent',h69,...
'Callback','trs_menucom(''new project'')',...
'Label','NEW PROJECT',...
'Tag','t',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 't';

h72 = uimenu(...
'Parent',h69,...
'Callback','QUIT_CURRENT',...
'Enable','off',...
'Label','QUIT PROJECT',...
'Tag','t',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 't';

h73 = uimenu(...
'Parent',h69,...
'Callback','trs_menucom(''keep data on disk'')',...
'Enable','off',...
'Label','keep data on disk',...
'Tag','t',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 't';

h74 = uimenu(...
'Parent',h69,...
'Callback','trs_menucom(''keep data in memory'')',...
'Enable','off',...
'Label','keep data in memory',...
'Tag','t',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 't';

h75 = uimenu(...
'Parent',h69,...
'Callback','trs_displayproperties',...
'Enable','off',...
'Label','display point properties',...
'Tag','t',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 't';

h76 = uimenu(...
'Parent',h69,...
'Callback','trs_menucom(''select used points'')',...
'Enable','off',...
'Label','select used point',...
'Tag','t',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 't';

h77 = uimenu(...
'Parent',h69,...
'Callback','trs_menucom(''plot rank vs signal'')',...
'Enable','off',...
'Label','plot rank vs signal',...
'Tag','t',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h78 = uimenu(...
'Parent',h69,...
'Callback','trs_makemedian()',...
'Enable','off',...
'Label','make median point',...
'Separator','on',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h79 = uimenu(...
'Parent',h69,...
'Callback','amc_menucom(''make median comparison'')',...
'Enable','off',...
'Label','make median comparison',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h80 = uimenu(...
'Parent',h69,...
'Callback','trs_findpairs(1)',...
'Enable','off',...
'Label','find couple of points',...
'Separator','on',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h81 = uimenu(...
'Parent',h69,...
'Callback','trs_treedata()',...
'Enable','off',...
'Label','prepare data for tree',...
'Separator','on',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h82 = uimenu(...
'Parent',h69,...
'Callback','trs_treedraw(1)',...
'Enable','off',...
'Label','plot tree',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h83 = uimenu(...
'Parent',h69,...
'Callback','COM_RAY(''prepare calibration'')',...
'Enable','off',...
'Label','prepare calibration',...
'Separator','on',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h84 = uimenu(...
'Parent',h69,...
'Callback','COM_RAY(''do calibration curve'')',...
'Enable','off',...
'Label','do calibration curve',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h85 = uimenu(...
'Parent',h69,...
'Callback','COM_RAY(''plot calibration curve'')',...
'Enable','off',...
'Label','plot calibration curve',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h86 = uimenu(...
'Parent',h69,...
'Callback','COM_RAY(''plot reproducibility'')',...
'Enable','off',...
'Label','plot reproductibility',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h87 = uimenu(...
'Parent',h69,...
'Callback','COM_RAY(''prepare project comparisons'')',...
'Enable','off',...
'Label','prepare project comparisons',...
'Separator','on',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h88 = uimenu(...
'Parent',h69,...
'Callback','COM_RAY(''make project comparisons'')',...
'Enable','off',...
'Label','make project comparisons',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h89 = uimenu(...
'Parent',h69,...
'Callback','COM_RAY(''make net group'')',...
'Enable','off',...
'Label','make net groups',...
'Separator','on',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h90 = uimenu(...
'Parent',h69,...
'Callback','COM_RAY(''prepare net comparison'',''full'')',...
'Enable','off',...
'Label','prepare net comparisons',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h91 = uimenu(...
'Parent',h69,...
'Callback','COM_RAY(''make net comparisons'')',...
'Enable','off',...
'Label','make net comparisons',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h92 = uimenu(...
'Parent',h69,...
'Callback','COM_RAY(''view error in comparison'')',...
'Enable','off',...
'Label','view error in net comparisons',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h93 = uimenu(...
'Parent',h69,...
'Callback','COM_RAY(''write comp table'')',...
'Enable','off',...
'Label','write net comparison tables',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h94 = uimenu(...
'Parent',h69,...
'Callback','COM_RAY(''write present table'')',...
'Enable','off',...
'Label','write biol present tables',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h95 = uimenu(...
'Parent',h69,...
'Callback','COM_RAY(''make comparison for non redundant biol cond'')',...
'Enable','off',...
'Label','make net comparison for non redundant biol cond',...
'Separator','on',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h96 = uimenu(...
'Parent',h69,...
'Callback','COM_RAY(''find non redundant biol cond'')',...
'Enable','off',...
'Label','find non redundant biol cond',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h97 = uimenu(...
'Parent',h69,...
'Callback','COM_RAY(''print results'')',...
'Enable','off',...
'Label','print results',...
'Separator','on',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'Untitled_31';

h98 = uimenu(...
'Parent',h69,...
'Callback','COM_RAY(''print results for promotor search'')',...
'Enable','off',...
'Label','print results for promotor search',...
'Tag','Untitled_31',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h99 = uimenu(...
'Parent',h69,...
'Callback','COM_RAY(''export results to go'')',...
'Enable','off',...
'Label','export results to GO',...
'Separator','on',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'Untitled_19';

h100 = uimenu(...
'Parent',h69,...
'Callback','COM_RAY(''write results in GO clusters'')',...
'Enable','off',...
'Label','write results in GO clusters',...
'Tag','Untitled_19',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'Untitled_22';

h101 = uimenu(...
'Parent',h69,...
'Callback','COM_RAY(''display on keiko'',''result'')',...
'Enable','off',...
'Label','display results on keiko',...
'Separator','on',...
'Tag','Untitled_22',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h102 = uimenu(...
'Parent',h69,...
'Callback','COM_RAY(''export results to Gene DIVER'')',...
'Enable','off',...
'Label','export results to Gene DIVER',...
'Separator','on',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h103 = uimenu(...
'Parent',h69,...
'Callback','COM_RAY(''import Gene DIVER clustering'')',...
'Enable','off',...
'Label','import Gene DIVER clustering',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h104 = uimenu(...
'Parent',h69,...
'Callback','COM_RAY(''write Gene DIVER clustering'')',...
'Enable','off',...
'Label','write Gene DIVER clustering',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h105 = uimenu(...
'Parent',h69,...
'Callback','COM_RAY(''export top list to GENERATOR'')',...
'Enable','off',...
'Label','export top list to GENERATOR',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h106 = uimenu(...
'Parent',h69,...
'Callback','COM_RAY(''export project clusters to GENERATOR'')',...
'Enable','off',...
'Label','export clusters to GENERATOR',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h107 = uimenu(...
'Parent',h69,...
'Callback','COM_RAY(''print Gene DIVER clustering'')',...
'Enable','off',...
'Label','print Gene DIVER clustering',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h108 = uimenu(...
'Parent',h69,...
'Callback','COM_RAY(''write top lists'')',...
'Enable','off',...
'Label','write top lists',...
'Separator','on',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h109 = uimenu(...
'Parent',h1,...
'Label','CHIPCHIP',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h110 = uimenu(...
'Parent',h109,...
'Callback','COM_RAY(''keep data on disk'')',...
'Label','keep data on disk',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h111 = uimenu(...
'Parent',h109,...
'Callback','COM_RAY(''plot rank vs signal'')',...
'Label','plot rank vs signal',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'Untitled_10';

h112 = uimenu(...
'Parent',h109,...
'Callback','MAKE_VAR_ALL(''chipchip rank'')',...
'Label','test vs control : rank & signal',...
'Tag','Untitled_10',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'Untitled_11';

h113 = uimenu(...
'Parent',h109,...
'Callback','COM_RAY(''make unique group'')',...
'Label','make groups',...
'Tag','Untitled_11',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h114 = uimenu(...
'Parent',h109,...
'Callback','COM_RAY(''do calibration curve'')',...
'Label','do calibration curve',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h115 = uimenu(...
'Parent',h109,...
'Callback','COM_RAY(prepare chipchip comparison'')',...
'Label','prepare comparisons',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'Untitled_14';

h116 = uimenu(...
'Parent',h109,...
'Callback','COM_RAY(''make chipchip comparison'')',...
'Label','make comparisons',...
'Tag','Untitled_14',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h117 = uimenu(...
'Parent',h109,...
'Callback','COM_RAY(''plot chipchip tree'')',...
'Label','plot tree',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h118 = uimenu(...
'Parent',h109,...
'Callback','COM_RAY(''map chipchip result'')',...
'Label','map results',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'Untitled_15';

h119 = uimenu(...
'Parent',h109,...
'Callback','COM_RAY(''import pv values'')',...
'Label','import pv values',...
'Separator','on',...
'Tag','Untitled_15',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'Untitled_16';

h120 = uimenu(...
'Parent',h109,...
'Callback','COM_RAY(''write chipchip result'')',...
'Label','write result',...
'Tag','Untitled_16',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h121 = uimenu(...
'Parent',h1,...
'Label','PROBESET',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'Untitled_50';

h122 = uimenu(...
'Parent',h121,...
'Callback','COM_RAY(''number of genes by probe nb'')',...
'Label','number of genes by probe nb',...
'Tag','Untitled_50',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'Untitled_51';

h123 = uimenu(...
'Parent',h121,...
'Callback','COM_RAY(''import info on probesets'')',...
'Label','import info on probesets',...
'Tag','Untitled_51',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'Untitled_41';

h124 = uimenu(...
'Parent',h121,...
'Callback','COM_RAY(''calculate node similarity for probeset assignation'',1)',...
'Label','calculate node similarity for probesets targeting one gene',...
'Tag','Untitled_41',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'Untitled_52';

h125 = uimenu(...
'Parent',h121,...
'Callback','COM_RAY(''display node similarity for probesets'',1)',...
'Label','display node similarity for probeset targeting single gene',...
'Tag','Untitled_52',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'Untitled_53';

h126 = uimenu(...
'Parent',h121,...
'Callback','COM_RAY(''calculate node similarity for probeset assignation'',0)',...
'Label','calculate node similarity for probeset assignation',...
'Tag','Untitled_53',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'Untitled_54';

h127 = uimenu(...
'Parent',h121,...
'Callback','COM_RAY(''display node similarity for probesets'',0)',...
'Label','display node similarity for probeset assignation',...
'Tag','Untitled_54',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'Untitled_55';

h128 = uimenu(...
'Parent',h121,...
'Callback','COM_RAY(''merge probesets'')',...
'Label','merge probe sets',...
'Tag','Untitled_55',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h129 = uimenu(...
'Parent',h121,...
'Callback','COM_RAY(''import quality info'')',...
'Label','import info on quality',...
'Separator','on',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h130 = uimenu(...
'Parent',h121,...
'Callback','COM_RAY(''calculate probeset score'')',...
'Label','calculate score',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'Untitled_4';

h131 = uimenu(...
'Parent',h121,...
'Callback','COM_RAY(''display probeset score'')',...
'Label','display score',...
'Tag','Untitled_4',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h132 = uimenu(...
'Parent',h121,...
'Callback','COM_RAY(''Import info on duplicated probesets'')',...
'Label','import info on duplicated probesets',...
'Separator','on',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h133 = uimenu(...
'Parent',h121,...
'Callback','COM_RAY(''display quality info for duplicated probesets'')',...
'Label','display quality info for duplicated probesets',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h134 = uimenu(...
'Parent',h121,...
'Callback','COM_RAY(''write quality info for duplicated probesets'')',...
'Label','write quality info for duplicated probesets',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h135 = uimenu(...
'Parent',h121,...
'Callback','COM_RAY(''import info on chip to chip'')',...
'Label','import info on chip to chip',...
'Separator','on',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h136 = uimenu(...
'Parent',h1,...
'Checked','on',...
'Label','PS LIST',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h137 = uimenu(...
'Parent',h136,...
'Callback','COM_RAY(''write ensgeneid'','''',''index'')',...
'Label','index => ensgeneid',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h138 = uimenu(...
'Parent',h136,...
'Callback','COM_RAY(''write ensgeneid'','''',''probeset'','')',...
'Label','probeset => ensgeneid',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h139 = uimenu(...
'Parent',h136,...
'Callback','COM_RAY(''write ensgeneid'',''generator'',''index'')',...
'Label','index => ensgeneid for GENERATOR',...
'Separator','on',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h140 = uimenu(...
'Parent',h136,...
'Callback','COM_RAY(''write ensgeneid'',''generator'',''probeset'')',...
'Label','probeset => ensgeneid for GENERATOR',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h141 = uimenu(...
'Parent',h136,...
'Callback','COM_RAY(''write ensgeneid'',''generator'',''ensgeneid'')',...
'Label','ensgeneid => ensgeneid for GENERATOR',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h142 = uimenu(...
'Parent',h136,...
'Callback','COM_RAY(''write ensgeneid'',''ensgeneid'',''interspecies'')',...
'Label','ensgeneid sp1 => ensgeneid sp2',...
'Separator','on',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h143 = uimenu(...
'Parent',h136,...
'Callback','COM_RAY(''write index'')',...
'Label','probeset => index',...
'Separator','on',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'Untitled_29';

h144 = uimenu(...
'Parent',h136,...
'Callback','COM_RAY(''region distribution of a ps list'')',...
'Label','region distribution of a ps list',...
'Separator','on',...
'Tag','Untitled_29',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h145 = uimenu(...
'Parent',h136,...
'Callback','COM_RAY(''rank distribution of a ps list'')',...
'Label','rank distribution of a ps list',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'Untitled_30';

h146 = uimenu(...
'Parent',h136,...
'Callback','COM_RAY(''up and down biol cond for a ps list'')',...
'Label','up and down biol cond for a ps list',...
'Tag','Untitled_30',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h147 = uimenu(...
'Parent',h136,...
'Callback','COM_RAY(''write presence/absence'')',...
'Label','write chipset presence/absence (FT, property)',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h148 = uimenu(...
'Parent',h1,...
'Label','GO',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h149 = uimenu(...
'Parent',h148,...
'Callback','COM_RAY(''import generator list'')',...
'Label','import Generator list',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h150 = uimenu(...
'Parent',h148,...
'Callback','COM_RAY(''display generator list'')',...
'Label','display Generator list',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h151 = uimenu(...
'Parent',h148,...
'Callback','COM_RAY(''write GO content'',1,1)',...
'Label','write GO content for all',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h152 = uimenu(...
'Parent',h148,...
'Callback','COM_RAY(''write GO content'',1,0)',...
'Label','write GO content for one',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h153 = uimenu(...
'Parent',h1,...
'Label','UTILITIES',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h154 = uimenu(...
'Parent',h153,...
'Callback','COM_RAY(''change data format'')',...
'Label','change data format',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h155 = uimenu(...
'Parent',h153,...
'Callback','COM_RAY(''split into bloc of x100'')',...
'Label','split table files into bloc of x100 lines',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h156 = uimenu(...
'Parent',h153,...
'Callback','COM_RAY(''split net into bloc of x100'')',...
'Label','split net files in bloc of x100',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h157 = uimenu(...
'Parent',h153,...
'Callback','COM_RAY(''prepare net comparison'',''verification'')',...
'Label','verify comparisons',...
'Separator','on',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h158 = uimenu(...
'Parent',h153,...
'Callback','COM_RAY(''delete comparison'')',...
'Label','delete comparisons',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h159 = uimenu(...
'Parent',h153,...
'Callback','COM_RAY(''reorganize Comp files'')',...
'Label','reorganize comp files',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h160 = uimenu(...
'Parent',h153,...
'Callback','MAKESOFTLIST',...
'Label','update soft info',...
'Separator','on',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h161 = uimenu(...
'Parent',h153,...
'Callback','MAKEEXPLIST',...
'Label','update exp list',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h162 = uimenu(...
'Parent',h153,...
'Callback','MAKECHIPLIST',...
'Label','update chip list',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h163 = uimenu(...
'Parent',h153,...
'Callback','MAKENETLIST',...
'Label','update net list',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h164 = uimenu(...
'Parent',h153,...
'Callback','COM_RAY(''write network stat'')',...
'Label','write network stat files',...
'Separator','on',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h165 = uimenu(...
'Parent',h153,...
'Callback','COM_RAY(''write network connectivity'')',...
'Label','write network connectivity files',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h166 = uimenu(...
'Parent',h153,...
'Callback','COM_RAY(''write info for dataset'')',...
'Label','write info for dataset',...
'Separator','on',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h167 = uimenu(...
'Parent',h153,...
'Callback','COM_RAY(''write rank for dataset'')',...
'Label','write rank for dataset',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h168 = uimenu(...
'Parent',h153,...
'Callback','COM_RAY(''import chromosome info'')',...
'Label','import chromosome info',...
'Separator','on',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h169 = uimenu(...
'Parent',h153,...
'Callback','COM_RAY(''order network on chromosome info'')',...
'Label','order network on chromosome info',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h170 = uimenu(...
'Parent',h153,...
'Callback','COM_RAY(''display network on chromosome'')',...
'Label','display network on chromosome',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h171 = uimenu(...
'Parent',h153,...
'Callback','COM_RAY(''verify groups'')',...
'Label','verify groups',...
'Separator','on',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h172 = uimenu(...
'Parent',h1,...
'Label','ARTICLE',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h173 = uimenu(...
'Parent',h172,...
'Callback','BMC(''problem with astrocytes rank'')',...
'Label','pb astrocyte rang',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h174 = uimenu(...
'Parent',h172,...
'Callback','BMC(''problem with astrocytes signal'')',...
'Label','pb astrocyte signal',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h175 = uimenu(...
'Parent',h172,...
'Callback','BMC(''display comparison properties'')',...
'Label','display comparison properties',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h176 = uimenu(...
'Parent',h172,...
'Callback','BMC(''plot calibration curves'')',...
'Label','plot calibration curves',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h177 = uimenu(...
'Parent',h172,...
'Callback','BMC(''effect of technical replicate'')',...
'Label','effect of technical replicates',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h178 = uimenu(...
'Parent',h172,...
'Callback','BMC(''mean connectivity vs #comp'')',...
'Label','mean connectivity vs #comp',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h179 = uimenu(...
'Parent',h172,...
'Callback','BMC(''anti vs corr connectivity'')',...
'Label','anti vs corr connectivity',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h180 = uimenu(...
'Parent',h172,...
'Callback','BMC(''mean anti vs mean corr'')',...
'Label','mean anti vs mean corr',...
'Tag','''mean anti vs mean corr''',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h181 = uimenu(...
'Parent',h172,...
'Callback','BMC(''anti and corr distribution'')',...
'Label','mean corr and anti distribution',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h182 = uimenu(...
'Parent',h172,...
'Callback','BMC(''write stat on replicated probesets'')',...
'Label','write stat on replicated probesets',...
'Separator','on',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h183 = uimenu(...
'Parent',h172,...
'Callback','BMC(''write stat on net comparisons'')',...
'Label','write stat on net comparisons',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h184 = uimenu(...
'Parent',h172,...
'Callback','BMC(''display node similarity on replicated probesets'')',...
'Label','display node similarity on replicated probesets',...
'Separator','on',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = blanks(0);

h185 = uimenu(...
'Parent',h172,...
'Callback','BMC(''display node similarity between chipset'')',...
'Label','display node similarity between chipset',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'Untitled_57';

h186 = uimenu(...
'Parent',h1,...
'Label','PROG',...
'Tag','Untitled_57',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'Untitled_58';

h187 = uimenu(...
'Parent',h186,...
'Callback','prog(''reload amcmenu'')',...
'Label','reload amc menu',...
'Tag','Untitled_58',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );



% --- Set application data first then calling the CreateFcn. 
function local_CreateFcn(hObject, eventdata, createfcn, appdata)

if ~isempty(appdata)
   names = fieldnames(appdata);
   for i=1:length(names)
       name = char(names(i));
       setappdata(hObject, name, getfield(appdata,name));
   end
end

if ~isempty(createfcn)
   eval(createfcn);
end
